export type PageDefinition = { title: string; eyebrow: string; summary: string; sections: { title: string; body: string; items?: string[] }[] };

export const pages: Record<string, PageDefinition> = {
  services: { title: "Digital systems, organised around responsibility.", eyebrow: "SERVICES", summary: "Five connected practices cover the experience, the system behind it, the infrastructure below it, and the support that keeps it useful.", sections: [{ title: "Five practices", body: "Airix scopes work around the result an organisation needs, then brings in the right design, engineering, publishing, infrastructure, and support capabilities.", items: ["Digital Experiences", "Business Systems", "Publishing Technology", "Managed Infrastructure", "Support and Recovery"] }, { title: "Recurring operations", body: "Essential Care, Managed Growth, Digital Operations, and Publishing Operations create a clear path from delivery into accountable long-term service." }] },
  "services/digital-experiences": { title: "Digital experiences people can understand and act on.", eyebrow: "DIGITAL EXPERIENCES", summary: "Websites and commerce systems shaped around clarity, accessibility, performance, and measurable business journeys.", sections: [{ title: "What this practice covers", body: "Strategy and content come before implementation choices.", items: ["Website strategy", "UX and interface design", "Website development", "E-commerce", "SEO and content", "Accessibility and performance"] }, { title: "Built to keep improving", body: "Launch plans include measurement, ownership, maintenance, and a path for ongoing content and conversion improvement." }] },
  "services/business-systems": { title: "Move important work through a dependable system.", eyebrow: "BUSINESS SYSTEMS", summary: "Applications, portals, automations, integrations, and operational tools designed around real people and accountable service.", sections: [{ title: "Systems and workflows", body: "Automation supports human service rather than replacing human accountability.", items: ["Custom web applications", "Client and staff portals", "Operational dashboards", "Workflow automation", "API and payment integrations", "AI-assisted systems"] }, { title: "Designed around operations", body: "Airix maps roles, exceptions, data movement, and support before deciding what technology belongs in the solution." }] },
  "services/managed-infrastructure": { title: "The operating layer beneath the experience.", eyebrow: "MANAGED INFRASTRUCTURE", summary: "Hosting, cloud, servers, security, email, domains, backups, and monitoring managed as one coherent responsibility.", sections: [{ title: "Managed foundations", body: "Infrastructure decisions are tied to the systems and service levels they support.", items: ["Managed hosting", "VPS and cloud administration", "Domains and DNS", "Business and transactional email", "Backups and monitoring", "Security hardening"] }, { title: "Provider coordination", body: "Airix can work across hosting, email, domain, payment, and software providers so the client has one technical owner." }] },
  "services/support-recovery": { title: "Keep control. Recover it when necessary.", eyebrow: "SUPPORT AND RECOVERY", summary: "Ongoing maintenance and focused recovery for systems that are drifting, failing, compromised, or difficult to own.", sections: [{ title: "Continuity services", body: "Support is scoped around the system, risk, access, and purchased package.", items: ["Website and application maintenance", "OJS maintenance", "Technical audits", "Emergency recovery", "Failed-project rescue", "Migrations and upgrade planning"] }, { title: "No false emergency promises", body: "Submitting an urgent request outside business hours does not guarantee an immediate human response or resolution." }] },
  publishing: { title: "African journals deserve world-class publishing infrastructure.", eyebrow: "AIRIX PUBLISHING TECHNOLOGY", summary: "Specialist OJS systems, journal infrastructure, and publishing operations for journals, publishers, and universities.", sections: [{ title: "Platform engineering", body: "From a single journal to a multi-journal institutional platform.", items: ["New OJS installations", "Themes and plugins", "Upgrades and migrations", "Hosting, security, and recovery", "Payments and integrations", "Training and documentation"] }, { title: "Publishing operations", body: "Metadata, DOI and Crossref support, indexing readiness, editorial workflows, and agreed technical publishing support." }] },
  "publishing/ojs": { title: "OJS built for real publishing operations.", eyebrow: "OPEN JOURNAL SYSTEMS", summary: "Installation, design, extension, migration, recovery, and long-term operation with staging-led change control.", sections: [{ title: "The whole platform lifecycle", body: "Airix works across infrastructure, interface, editorial workflow, integrations, and support.", items: ["Installation and configuration", "Theme and plugin development", "Payment integration", "Upgrades and migrations", "Security and recovery", "Managed hosting and maintenance"] }] },
  "publishing/universities": { title: "A coherent journal platform for the institution.", eyebrow: "UNIVERSITIES", summary: "Shared infrastructure, clear governance, reusable workflows, and support for multiple journals without flattening their identities.", sections: [{ title: "Institutional foundations", body: "Plan journal onboarding, roles, themes, plugins, integrations, training, and platform operations as one programme." }] },
  "publishing/journal-platforms": { title: "One platform. Many journals. Clear ownership.", eyebrow: "JOURNAL PLATFORMS", summary: "Multi-journal OJS architecture designed for governance, consistency, and manageable long-term operations.", sections: [{ title: "Platform design", body: "Shared infrastructure and standards with room for distinct journal identities and workflows." }] },
  "publishing/hosting-support": { title: "Keep the journal available, secure, and supportable.", eyebrow: "HOSTING AND SUPPORT", summary: "Managed hosting, updates, backups, monitoring, security, and package-dependent support for publishing systems.", sections: [{ title: "Managed continuity", body: "Response commitments belong to the purchased package and contract, not a generic website promise." }] },
  "publishing/editorial-support": { title: "Technology that supports the publishing team.", eyebrow: "EDITORIAL SUPPORT", summary: "Workflow configuration, metadata support, DOI and Crossref assistance, indexing readiness, documentation, and training.", sections: [{ title: "Human accountability", body: "Tools and automation make publishing work clearer; editorial responsibility remains with people." }] },
  "publishing/plugins": { title: "OJS extensions shaped by publishing workflows.", eyebrow: "PLUGINS", summary: "Open-source and commercial plugin engineering across payments, access, fees, waivers, and institutional requirements.", sections: [{ title: "Clear commercial boundaries", body: "Open-source availability is distinct from installation, customisation, managed updates, and priority commercial support." }] },
  insights: { title: "Practical thinking for people who operate digital systems.", eyebrow: "AIRIX FIELD NOTES", summary: "Publishing technology, website operations, recovery, open-source releases, infrastructure, and workflow design without generic SEO filler.", sections: [{ title: "Featured guide", body: "How to prepare an OJS upgrade without turning production into a test environment." }, { title: "Resources", body: "Website and Digital Systems Health Checklist, plus an OJS Platform Health Check." }] },
  resources: { title: "Useful tools before you start a project.", eyebrow: "RESOURCES", summary: "Checklists, guides, and explainers that help organisations understand risk, scope, and next steps.", sections: [{ title: "Health checks", body: "Structured prompts for reviewing websites, digital systems, and OJS platforms before committing to change." }] },
  company: { title: "Small by design. Accountable by practice.", eyebrow: "COMPANY", summary: "Airix began with a goal of helping African businesses become more visible and grew into building and operating the systems behind that visibility.", sections: [{ title: "Why Airix exists", body: "The name carries ideas of family and partnership. Airix works inside the client’s organisation, with senior oversight on every engagement and responsibility after launch." }, { title: "Part of Airix 360", body: "Airix Media is the public creative-technology identity within Airix 360. Airix Food and Airix Store are sister ventures, not external clients." }] },
  partners: { title: "Specialist partners, clear accountability.", eyebrow: "PARTNERS", summary: "Airix collaborates with selected providers and specialists when a project needs capabilities beyond the core team.", sections: [{ title: "No badge wall", body: "Only verified, active partnerships will be published here." }] },
  careers: { title: "Build durable systems with us.", eyebrow: "CAREERS", summary: "There are no public roles listed in this prototype. Future opportunities will describe the actual work, context, and expectations.", sections: [{ title: "Small expert teams", body: "Airix values clarity, ownership, responsiveness, accessibility, and thoughtful technical decisions." }] },
  support: { title: "Support that matches the system and the agreement.", eyebrow: "SUPPORT", summary: "Choose standard support, an existing-client route, or emergency recovery. Coverage and response commitments depend on the purchased package.", sections: [{ title: "Standard support", body: "Maintenance, audits, migrations, updates, documentation, and ongoing improvements." }, { title: "Existing clients", body: "Use the client portal or your authenticated support path for project-specific help." }, { title: "Emergency recovery", body: "Provide symptoms, access status, recent changes, impact, and any available backups." }] },
  "support/emergency": { title: "Describe the emergency clearly.", eyebrow: "EMERGENCY RECOVERY", summary: "Use this route for an unavailable, compromised, corrupted, or severely impaired production system.", sections: [{ title: "Before submitting", body: "An initial diagnostic may be chargeable. Response depends on availability and package. Submission outside business hours does not guarantee immediate resolution.", items: ["Affected URL and system", "What users see", "When it started", "Recent changes", "Available access and backups"] }] },
  "knowledge-base": { title: "Answers for operating the system.", eyebrow: "KNOWLEDGE BASE", summary: "A prototype structure for platform, publishing, hosting, security, billing, and support guidance.", sections: [{ title: "Publishing platforms", body: "OJS administration, workflow, upgrades, plugins, and editorial operations." }, { title: "Websites and infrastructure", body: "Access, hosting, domains, email, backups, monitoring, and recovery." }] },
  status: { title: "Service status", eyebrow: "STATUS PROTOTYPE", summary: "No live monitoring data is connected in this prototype.", sections: [{ title: "Public website", body: "Prototype status only. A future adapter will publish verified service-state data." }, { title: "Client portal", body: "The portal is technically separate and does not control public-site availability." }] },
  security: { title: "Security is an operating practice.", eyebrow: "SECURITY", summary: "Airix designs for controlled access, secure defaults, backups, monitoring, recovery, and documented responsibility.", sections: [{ title: "Responsible disclosure", body: "Report suspected security issues privately to hello@airixmedia.com. Do not include secrets in an initial message." }, { title: "No invented certifications", body: "Only verified controls, providers, and certifications will be published." }] },
  "service-levels": { title: "Service levels are package-dependent.", eyebrow: "SERVICE LEVELS", summary: "Contracted commitments override general website information. Emergency availability is not the same as guaranteed resolution.", sections: [{ title: "Coverage", body: "Coverage varies by system, provider, access, and the active agreement." }, { title: "Response and resolution", body: "A response confirms receipt and triage. Resolution depends on diagnosis, dependencies, access, and scope." }] },
  legal: { title: "Legal centre", eyebrow: "DRAFT FOR LEGAL REVIEW", summary: "The following structure is not final legal advice and must be reviewed before publication.", sections: [{ title: "Contents", body: "Privacy, cookies, website terms, service terms, refunds and cancellation, regional pricing, accessibility, acceptable use, and data processing.", items: ["Privacy", "Cookies", "Website terms", "Service terms", "Refund and cancellation principles", "Regional pricing", "Accessibility", "Acceptable use", "Data processing"] }] },
  contact: { title: "Tell us what needs to work better.", eyebrow: "CONTACT", summary: "For new projects, the structured brief gives Airix the context needed to recommend a useful next step.", sections: [{ title: "Direct contact", body: "hello@airixmedia.com · +234 905 091 7937" }, { title: "WhatsApp", body: "Use the Nigerian number for calls and WhatsApp, or the United States number for WhatsApp only." }] },
  book: { title: "Consultation follows a useful brief.", eyebrow: "DISCOVERY CALL", summary: "Qualified prospects can book a free discovery call after Airix reviews the project context. No private calendar details are exposed here.", sections: [{ title: "Before the call", body: "Submit the project brief so the conversation can focus on decisions, risks, fit, and next steps." }] },
  "project-brief": { title: "Build a useful project brief.", eyebrow: "PROJECT BRIEF", summary: "The structured selector collects the context Airix needs to recommend a practice and next step.", sections: [{ title: "Continue to the selector", body: "Use Start a Project to save, print, email, or submit a preliminary brief." }] },
};

export function getPageDefinition(path: string) {
  if (pages[path]) return pages[path];
  if (path.startsWith("insights/")) return { title: "Planning an OJS upgrade without testing in production", eyebrow: "PUBLISHING OPERATIONS", summary: "A practical guide to inventory, compatibility, staging, validation, rollback, and communication.", sections: [{ title: "Start with an inventory", body: "Document the OJS version, plugins, theme, hosting, integrations, scheduled jobs, email, backups, and editorial calendar." }, { title: "Prove the path in staging", body: "Restore a representative copy, run the upgrade, validate critical editorial actions, and rehearse rollback before production." }] };
  if (path.startsWith("resources/")) return { title: "Digital Systems Health Checklist", eyebrow: "DOWNLOADABLE RESOURCE", summary: "A structured review of ownership, access, content, performance, security, analytics, backups, and support.", sections: [{ title: "Use it before scoping", body: "The checklist helps surface missing access, unclear ownership, fragile dependencies, and work that should happen before a rebuild." }] };
  return null;
}

const translatedCritical: Record<"fr" | "pt", Record<string, PageDefinition>> = {
  fr: {
    publishing: { title: "Les revues africaines méritent une infrastructure de publication de classe mondiale.", eyebrow: "AIRIX PUBLISHING TECHNOLOGY", summary: "Systèmes OJS spécialisés, infrastructure de revues et opérations éditoriales pour les revues, éditeurs et universités.", sections: [{ title: "Ingénierie de plateforme", body: "D’une revue unique à une plateforme institutionnelle multi-revues.", items: ["Installation OJS", "Thèmes et extensions", "Mises à niveau et migrations", "Hébergement et sécurité", "Paiements et intégrations", "Formation et documentation"] }, { title: "Opérations éditoriales", body: "Métadonnées, DOI, Crossref, préparation à l’indexation, flux éditoriaux et assistance technique convenue." }] },
    legal: { title: "Centre juridique", eyebrow: "PROJET À FAIRE VALIDER", summary: "Cette structure ne constitue pas un avis juridique final et doit être révisée avant publication.", sections: [{ title: "Sommaire", body: "Confidentialité, cookies, conditions du site, services, remboursements, tarification régionale, accessibilité, utilisation acceptable et traitement des données." }] },
  },
  pt: {
    publishing: { title: "As revistas africanas merecem uma infraestrutura de publicação de classe mundial.", eyebrow: "AIRIX PUBLISHING TECHNOLOGY", summary: "Sistemas OJS especializados, infraestrutura de revistas e operações editoriais para revistas, editoras e universidades.", sections: [{ title: "Engenharia de plataforma", body: "De uma única revista a uma plataforma institucional com várias publicações.", items: ["Instalação OJS", "Temas e extensões", "Atualizações e migrações", "Alojamento e segurança", "Pagamentos e integrações", "Formação e documentação"] }, { title: "Operações editoriais", body: "Metadados, DOI, Crossref, preparação para indexação, fluxos editoriais e suporte técnico acordado." }] },
    legal: { title: "Centro jurídico", eyebrow: "RASCUNHO PARA REVISÃO", summary: "Esta estrutura não é aconselhamento jurídico final e deve ser revista antes da publicação.", sections: [{ title: "Conteúdo", body: "Privacidade, cookies, termos do site, serviços, reembolsos, preços regionais, acessibilidade, utilização aceitável e tratamento de dados." }] },
  },
};

export function getLocalisedPageDefinition(path: string, locale: "en" | "fr" | "pt") {
  if (locale !== "en" && translatedCritical[locale][path]) return translatedCritical[locale][path];
  return getPageDefinition(path);
}
