import { expect,test } from "@playwright/test";

const routes=["/internal/atlas-studio","/internal/atlas-trust","/internal/atlas-labs"] as const;

test("all W6 routes are private, candidate-gated, and use approved navigation",async({page},info)=>{for(const route of routes){await page.goto(route);await expect(page.locator('meta[name="robots"]')).toHaveAttribute("content",/noindex/);await expect(page.locator('meta[name="robots"]')).toHaveAttribute("content",/nofollow/);await expect(page.locator("[data-asset-status='candidate']")).toHaveCount(1);await expect(page.getByText("Not approved for public use",{exact:true})).toBeVisible();if(info.project.name==="mobile")await page.getByRole("button",{name:/Menu/}).click();const navigation=page.getByRole("navigation",{name:info.project.name==="mobile"?"Mobile primary navigation":"Primary navigation"});const labels=await navigation.getByRole("link").allTextContents();expect(labels.join(" ")).toMatch(/Work.*Services.*Publishing.*Atlas.*Studio.*Discuss a Project/);if(info.project.name==="mobile")await page.keyboard.press("Escape")}});
test("Studio carries Edo identity, process, principles, and boutique boundaries",async({page})=>{await page.goto("/internal/atlas-studio");await expect(page.locator("[data-atlas-state='edo']")).toBeVisible();await expect(page.locator("[data-studio-process] > li")).toHaveCount(5);await expect(page.getByRole("heading",{name:"Small by design. Accountable by practice."})).toBeVisible();await expect(page.locator("body")).toContainText("no employee count")});
test("Trust carries Edo identity, evidence states, responsibility, and visible limitations",async({page})=>{await page.goto("/internal/atlas-trust");await expect(page.locator("[data-atlas-state='edo']")).toBeVisible();await expect(page.locator("[data-trust-register] > li")).toHaveCount(6);await expect(page.locator("[data-responsibility-boundaries] > div")).toHaveCount(4);await expect(page.getByRole("heading",{name:"Not verified is not hidden."})).toBeVisible()});
test("Labs carries Kaduna identity and five real repository release records",async({page})=>{await page.goto("/internal/atlas-labs");await expect(page.locator("[data-atlas-state='kaduna']")).toBeVisible();await expect(page.locator("[data-labs-project-textual-equivalent] > li")).toHaveCount(5);for(const release of ["v1.1.1.0","v1.2.1","v1.4.0.0","v1.0.2.0","v1.0.0.0"])await expect(page.getByText(new RegExp(release.replaceAll(".","\\."))).first()).toBeVisible();await expect(page.getByRole("link",{name:/Inspect OJS Paystack/})).toHaveAttribute("href","https://github.com/thathman/PaystackOJS")});
test("Labs project register supports keyboard navigation",async({page})=>{await page.goto("/internal/atlas-labs#experiment-registry");const tabs=page.getByRole("tablist",{name:"Open-source projects"}).getByRole("tab");await tabs.first().focus();await page.keyboard.press("End");await expect(tabs.last()).toBeFocused();await expect(page.getByRole("heading",{name:"Request Waiver for OJS"})).toBeVisible();await page.keyboard.press("Home");await expect(tabs.first()).toBeFocused()});
test("state orientation stays contextual and provides a wider-Atlas return",async({page})=>{await page.goto("/internal/atlas-studio");const state=page.locator("[data-atlas-state='edo']");await expect(state).toContainText("Airix Atlas");await expect(state).toContainText("Edo State");await expect(state.getByRole("link",{name:/Return to the wider Atlas/})).toHaveAttribute("href","/atlas");await expect(page.locator("[data-transition-mode='road']")).toContainText("Stewardship Register")});
test("no fabricated trust or project metrics appear as claims",async({page})=>{for(const route of ["/internal/atlas-trust","/internal/atlas-labs"]){await page.goto(route);await expect(page.getByText("99.9% uptime",{exact:true})).toHaveCount(0);await expect(page.getByText("Certified secure",{exact:true})).toHaveCount(0);await expect(page.getByText("24/7 guaranteed support",{exact:true})).toHaveCount(0);await expect(page.getByText(/\d+[,+]? downloads/i,{exact:true})).toHaveCount(0);await expect(page.getByText(/\d+[,+]? customers/i,{exact:true})).toHaveCount(0)}});
test("reduced motion preserves identity, process, evidence, and actions",async({page})=>{await page.emulateMedia({reducedMotion:"reduce"});for(const route of routes){await page.goto(route);await expect(page.locator("[data-atlas-state]")).toBeVisible();await expect(page.locator("main h1")).toBeVisible();await expect(page.getByRole("link",{name:/Return to the wider Atlas/})).toBeVisible()}await page.goto("/internal/atlas-labs");await expect(page.locator("[data-experiment-route] > li")).toHaveCount(6);await expect(page.locator("[data-experiment-route] > li").first()).toHaveCSS("animation-name","none")});
test("scene and decorative handling preserve meaningful alternatives",async({page})=>{for(const route of routes){await page.goto(route);const images=page.locator("img");for(let index=0;index<await images.count();index++){const image=images.nth(index);const alt=await image.getAttribute("alt");const hidden=await image.getAttribute("aria-hidden");expect(Boolean(alt?.trim())||hidden==="true").toBeTruthy()}}});
test("opening scenes request responsive derivatives and never source masters",async({page})=>{for(const route of routes){const requests:string[]=[];page.on("request",request=>requests.push(request.url()));await page.goto(route);await expect(page.locator("[data-asset-status='candidate'] img")).toBeVisible();expect(requests.some(url=>url.includes("/images/atlas/states/")&&url.endsWith(".webp"))).toBeTruthy();expect(requests.some(url=>url.includes("/images/atlas/states/")&&(url.includes("/source/")||url.endsWith(".png")))).toBeFalsy()}});
test("skip targets and mobile menu remain keyboard accessible",async({page},info)=>{await page.goto("/internal/atlas-studio");const skip=page.getByRole("link",{name:"Skip to Studio process"});await skip.focus();await page.keyboard.press("Enter");await expect(page.locator("#studio-process")).toBeFocused();if(info.project.name==="mobile"){const trigger=page.getByRole("button",{name:/Menu/});await trigger.click();await expect(page.getByRole("dialog",{name:"Atlas navigation"})).toBeVisible();await page.keyboard.press("Escape");await expect(trigger).toBeFocused()}});
test("public homepage, Studio, and open-source routes remain isolated",async({page})=>{for(const route of ["/","/company","/open-source"]){await page.goto(route);await expect(page.locator("a[href^='/internal/atlas-']")).toHaveCount(0);await expect(page.locator("[data-w6-review]")).toHaveCount(0);await expect(page.getByText("Private W6 review",{exact:true})).toHaveCount(0)}});
