import path from "node:path";
import { expect, test, type Page } from "@playwright/test";

const output = (name: string) => path.join(process.cwd(), "output/playwright/atlas-infrastructure-w5", name);
async function capture(page: Page, hash: string, selector: string, name: string) { await page.goto(`/internal/atlas-infrastructure${hash}`); const subject = page.locator(selector).first(); await expect(subject).toBeVisible(); await subject.scrollIntoViewIfNeeded(); await page.waitForTimeout(200); await page.screenshot({ path: output(name), animations: "disabled", scale: "css" }); }

test("capture W5 desktop evidence", async ({ page }, info) => { test.skip(info.project.name !== "desktop", "Desktop evidence runs once."); await page.setViewportSize({ width:1440,height:1000 }); await capture(page,"","[data-atlas-infrastructure]","desktop-opening-1440x1000.png"); await capture(page,"#infrastructure-capabilities","[data-operating-layers]","desktop-operating-layers-1440x1000.png"); await capture(page,"#monitoring-continuity","[data-service-level-summary]","desktop-continuity-1440x1000.png"); await capture(page,"#recovery-route","[data-recovery-route]","desktop-recovery-1440x1000.png"); await capture(page,"#integration-transit","[data-integration-textual-equivalent]","desktop-integrations-1440x1000.png"); await capture(page,"#emergency-support","[data-emergency-support]","desktop-emergency-1440x1000.png"); });
test("capture W5 mobile evidence", async ({ page }, info) => { test.skip(info.project.name !== "mobile", "Mobile evidence runs once."); await page.setViewportSize({ width:390,height:844 }); await capture(page,"","[data-atlas-infrastructure]","mobile-opening-390x844.png"); await capture(page,"#infrastructure-capabilities","[data-operating-layers]","mobile-operating-layers-390x844.png"); await capture(page,"#recovery-route","[data-recovery-route]","mobile-recovery-390x844.png"); await capture(page,"#emergency-support","[data-emergency-support]","mobile-emergency-390x844.png"); });
test("capture W5 reduced-motion evidence", async ({ page }, info) => { test.skip(info.project.name !== "desktop", "Reduced evidence runs once."); await page.setViewportSize({ width:1440,height:1000 }); await page.emulateMedia({ reducedMotion:"reduce" }); await capture(page,"","[data-atlas-infrastructure]","reduced-motion-opening-1440x1000.png"); await capture(page,"#recovery-route","[data-recovery-route]","reduced-motion-recovery-1440x1000.png"); });
