"use client";
import {useState,type FormEvent} from "react";
import {projectRoutes} from "@/content/atlas/w7";
import styles from "./atlas-w7.module.css";

export function ProjectRouteSelector(){const[selected,setSelected]=useState("uncertain");return <div><ul className={styles.routes} aria-label="Project routes">{projectRoutes.map(([id,name,detail])=><li key={id}><button type="button" aria-pressed={selected===id} onClick={()=>setSelected(id)}>{name}</button><p>{detail}</p></li>)}</ul><p className={styles.summary} role="status"><strong>Selected route:</strong> {projectRoutes.find(([id])=>id===selected)?.[1]}. This preview selection is held only in component memory and is not submitted.</p></div>}

function text(form:HTMLFormElement,name:string){return new FormData(form).get(name)?.toString().trim()??""}
export function ContactReviewForm(){const[errors,setErrors]=useState<string[]>([]);const[preview,setPreview]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const next=[] as string[];if(!text(f,"name"))next.push("Enter your name.");if(!/^\S+@\S+\.\S+$/.test(text(f,"email")))next.push("Enter a valid email address.");if(text(f,"message").length<20)next.push("Describe the enquiry in at least 20 characters.");setErrors(next);setPreview(next.length===0)}return <form className={styles.form} noValidate onSubmit={submit} data-network-mode="none"><p className={styles.notice}>Internal review — no information is transmitted.</p>{errors.length?<div className={styles.errorSummary} role="alert" tabIndex={-1}><strong>Check the enquiry</strong><ul>{errors.map(x=><li key={x}>{x}</li>)}</ul></div>:null}<div className={styles.formGrid}><div className={styles.field}><label htmlFor="contact-name">Name</label><input id="contact-name" name="name" autoComplete="name"/></div><div className={styles.field}><label htmlFor="contact-email">Email</label><input id="contact-email" name="email" type="email" autoComplete="email" inputMode="email"/></div><div className={styles.field}><label htmlFor="contact-route">Enquiry route</label><select id="contact-route" name="route"><option>General enquiry</option><option>Project enquiry</option><option>Publishing enquiry</option><option>Collaboration enquiry — scope unverified</option></select></div><div className={styles.field} data-full="true"><label htmlFor="contact-message">What do you need help with?</label><textarea id="contact-message" name="message" aria-describedby="contact-help"/><small id="contact-help">Do not include passwords, credentials, financial information or other secrets.</small></div></div><button type="submit">Review enquiry locally</button>{preview?<div className={styles.summary} role="status"><strong>Local preview complete.</strong><p>No email, CRM record or network request was created. Use the verified email link if you choose to contact Airix.</p></div>:null}</form>}

export function BookingReviewForm(){const[errors,setErrors]=useState<string[]>([]);const[preview,setPreview]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const next=[] as string[];for(const [name,label] of [["purpose","Choose a meeting purpose."],["family","Choose a service family."],["stage","Choose a project stage."],["timezone","Enter a preferred time zone."],["timing","Describe preferred timing."]] as const)if(!text(f,name))next.push(label);setErrors(next);setPreview(next.length===0)}return <form className={styles.form} noValidate onSubmit={submit} data-network-mode="none"><p className={styles.notice}>Internal review — no information is transmitted. No live calendar or available times are connected.</p>{errors.length?<div className={styles.errorSummary} role="alert"><strong>Prepare the booking request</strong><ul>{errors.map(x=><li key={x}>{x}</li>)}</ul></div>:null}<div className={styles.formGrid}><div className={styles.field}><label htmlFor="book-purpose">Meeting purpose</label><select id="book-purpose" name="purpose"><option value="">Choose</option><option>Project discovery</option><option>Publishing consultation</option><option>Technical scoping</option></select></div><div className={styles.field}><label htmlFor="book-family">Service family</label><select id="book-family" name="family"><option value="">Choose</option>{projectRoutes.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div><div className={styles.field}><label htmlFor="book-stage">Project stage</label><select id="book-stage" name="stage"><option value="">Choose</option><option>Exploring</option><option>Ready to scope</option><option>Existing system</option><option>Recovery need</option></select></div><div className={styles.field}><label htmlFor="book-timezone">Preferred time zone</label><input id="book-timezone" name="timezone" placeholder="Africa/Lagos" aria-describedby="timezone-help"/><small id="timezone-help">Use an IANA name or city and UTC offset.</small></div><div className={styles.field} data-full="true"><label htmlFor="book-timing">Preferred timing</label><input id="book-timing" name="timing" placeholder="For example: weekday mornings next month"/></div><div className={styles.field} data-full="true"><label htmlFor="book-notes">Preparation notes</label><textarea id="book-notes" name="notes"/><small>Do not include secrets. Privacy and consent wording requires legal approval.</small></div></div><button type="submit">Review preparation locally</button>{preview?<div className={styles.summary} role="status"><strong>Preparation preview complete.</strong><p>No appointment was created and no availability is implied. A verified scheduling integration remains future work.</p></div>:null}</form>}
