export type PublicState = "lagos" | "oyo" | "rivers" | "edo" | "kaduna" | "plateau" | "ogun" | "shared";

export type PublicPage = {
  path: string;
  state: PublicState;
  stateLabel: string;
  eyebrow: string;
  title: string;
  summary: string;
  art?: "lagos-arrival" | "oyo-publishing" | "oyo-workflow" | "oyo-migration" | "oyo-open-source" | "rivers-infrastructure" | "rivers-support" | "rivers-emergency" | "edo-studio" | "kaduna-labs" | "plateau-observatory" | "plateau-insights" | "plateau-resources" | "ogun-gateway" | "ogun-contact" | "ogun-booking";
  sections: Array<{ title: string; body: string; items?: string[] }>;
  action?: { label: string; href: string };
};

const serviceSections = {
  digital: [
    { title: "Clear on the surface. Accountable underneath.", body: "Strategy, content, interaction, engineering and performance are treated as one customer journey.", items: ["Website strategy and content architecture", "UX and accessible interface design", "Website and web-application engineering", "Commerce, payments and service journeys", "Measurement, SEO and performance"] },
    { title: "Built to remain useful", body: "Every launch needs ownership, documentation, maintenance and a path for measured improvement." },
  ],
  systems: [
    { title: "Work moves through people, rules and exceptions.", body: "Airix maps those realities before choosing the platform or integration.", items: ["Custom applications", "Client and staff portals", "Workflow automation", "API and payment integrations", "Operational dashboards", "Data migration and handoff"] },
    { title: "One visible responsibility", body: "Customer experience, operational record, external services and long-term support are designed as one connected system." },
  ],
};

export const publicPages: PublicPage[] = [
  { path: "work", state: "lagos", stateLabel: "Lagos · Landmarks", eyebrow: "WORK", title: "Proof lives in the system, not the pitch.", summary: "A restrained record of public evidence, responsibilities and work that can be verified.", art: "lagos-arrival", sections: [{ title: "Current public proof", body: "KU Journals has a source-captured public interface whose footer credits Airix Media with design, development and maintenance. Broader project narratives and outcomes remain withheld until evidence and permission are complete." }, { title: "Evidence standard", body: "Real interfaces replace decorative browser frames. Missing constraints, responsibilities or outcomes are named rather than invented." }], action: { label: "Discuss a related system", href: "/discuss" } },
  { path: "services", state: "lagos", stateLabel: "Lagos · Commerce", eyebrow: "SERVICES", title: "Build. Run. Rescue.", summary: "Digital experiences, operating systems and infrastructure organised around responsibility across the life of the work.", art: "lagos-arrival", sections: [{ title: "Build", body: "Websites, commerce, applications, portals, publishing platforms and integrations." }, { title: "Run", body: "Hosting, maintenance, monitoring, documentation and operational improvement." }, { title: "Rescue", body: "Audits, migrations, recovery and control restored to systems that have drifted or failed." }], action: { label: "Choose a service route", href: "/discuss" } },
  { path: "services/digital-experiences", state: "lagos", stateLabel: "Lagos · Commerce", eyebrow: "DIGITAL EXPERIENCES", title: "Make the first interaction clear, fast and useful.", summary: "Websites and commerce systems shaped around real customer journeys and dependable operations.", art: "lagos-arrival", sections: serviceSections.digital, action: { label: "Discuss a digital experience", href: "/discuss" } },
  { path: "services/business-systems", state: "lagos", stateLabel: "Lagos · Commerce", eyebrow: "BUSINESS SYSTEMS", title: "Move important work through a system people can trust.", summary: "Applications, portals, automation and integrations grounded in the way the organisation actually operates.", art: "lagos-arrival", sections: serviceSections.systems, action: { label: "Discuss an operating system", href: "/discuss" } },
  { path: "services/managed-infrastructure", state: "rivers", stateLabel: "Rivers · Infrastructure", eyebrow: "MANAGED INFRASTRUCTURE", title: "Keep the operating layer visible, maintained and recoverable.", summary: "Hosting, domains, email, backups, monitoring and provider coordination treated as one practical responsibility.", art: "rivers-infrastructure", sections: [{ title: "Operating foundations", body: "Infrastructure choices follow the system, access model, risks and agreement.", items: ["Managed hosting and server administration", "Domains, DNS and SSL", "Business and transactional email", "Backups and monitoring", "Security hardening", "Provider and integration coordination"] }, { title: "No decorative uptime claims", body: "Availability, response and recovery commitments belong to a verified agreement. This site does not invent them." }], action: { label: "Discuss infrastructure", href: "/discuss" } },
  { path: "services/support-recovery", state: "rivers", stateLabel: "Rivers · Continuity", eyebrow: "SUPPORT & RECOVERY", title: "Maintain control. Recover it when necessary.", summary: "Ongoing care and focused recovery for systems that cannot be allowed to drift.", art: "rivers-support", sections: [{ title: "Continuity work", body: "Maintenance, technical audits, migrations, documentation and measured improvement." }, { title: "Recovery work", body: "Triage, evidence preservation, access recovery, staged repair, validation and handover. Timing and outcome depend on diagnosis and access." }], action: { label: "Open support", href: "/support" } },
  { path: "publishing", state: "oyo", stateLabel: "Oyo · Knowledge", eyebrow: "PUBLISHING TECHNOLOGY", title: "African journals deserve world-class publishing infrastructure.", summary: "OJS platforms, editorial systems and long-term technical operations for journals, publishers and universities.", art: "oyo-publishing", sections: [{ title: "Publishing is an operating system", body: "The platform connects submissions, people, review, metadata, production, payments, discovery and preservation." }, { title: "From foundation to continuity", body: "Airix works across installation, themes, plugins, migrations, hosting, security, training, documentation and publishing support." }], action: { label: "Discuss a publishing platform", href: "/discuss" } },
  { path: "publishing/ojs", state: "oyo", stateLabel: "Oyo · Editorial route", eyebrow: "OPEN JOURNAL SYSTEMS", title: "OJS built around real editorial operations.", summary: "Configuration, extension, migration, recovery and long-term operation with staging-led change control.", art: "oyo-workflow", sections: [{ title: "A configurable workflow", body: "Submission, assessment, review, revision, production, publication and discovery are shown as an illustrative model—not a universal journal process." }, { title: "Platform lifecycle", body: "Installation, multi-journal architecture, themes, plugins, payments, upgrades, migration, training, hosting and maintenance." }], action: { label: "Plan an OJS project", href: "/discuss" } },
  { path: "publishing/universities", state: "oyo", stateLabel: "Oyo · Institutional publishing", eyebrow: "UNIVERSITIES", title: "One publishing foundation. Distinct journals. Clear governance.", summary: "Shared OJS infrastructure with room for journal identity, editorial autonomy and manageable institutional operations.", art: "oyo-publishing", sections: [{ title: "Institutional architecture", body: "Governance, onboarding, roles, themes, plugins, integrations, training and support planned as one programme." }] },
  { path: "publishing/journal-platforms", state: "oyo", stateLabel: "Oyo · Journal platforms", eyebrow: "JOURNAL PLATFORMS", title: "Build a platform the publishing team can own.", summary: "Single- and multi-journal OJS systems designed for clear responsibility and long-term operation.", art: "oyo-workflow", sections: [{ title: "Platform design", body: "Shared infrastructure and standards with appropriate identity, workflow and access boundaries for each journal." }] },
  { path: "publishing/hosting-support", state: "rivers", stateLabel: "Oyo to Rivers · Continuity", eyebrow: "PUBLISHING HOSTING & SUPPORT", title: "Keep the journal available, secure and supportable.", summary: "A publishing platform needs both editorial understanding and maintained operating infrastructure.", art: "rivers-support", sections: [{ title: "Managed continuity", body: "Hosting, updates, backups, monitoring, security, documentation and package-dependent support." }, { title: "Terms remain explicit", body: "Response commitments and coverage belong to the purchased package and agreement." }] },
  { path: "publishing/editorial-support", state: "oyo", stateLabel: "Oyo · Editorial operations", eyebrow: "EDITORIAL SUPPORT", title: "Technology that supports the publishing team.", summary: "Workflow configuration, metadata assistance, DOI and Crossref implementation support, documentation and training.", art: "oyo-publishing", sections: [{ title: "People remain accountable", body: "Tools can make publishing work clearer. Editorial decisions, policies and scholarly responsibility remain human." }] },
  { path: "publishing/plugins", state: "oyo", stateLabel: "Oyo to Kaduna · Open engineering", eyebrow: "OJS PLUGINS", title: "Extensions shaped by publishing workflows.", summary: "Verified public repositories across payments, access, submission fees, multi-provider payments and waiver requests.", art: "oyo-open-source", sections: [{ title: "Open-source boundaries", body: "Public code is distinct from installation, compatibility work, customisation, maintenance and commercial support." }, { title: "Release clarity", body: "PaystackOJS currently has a GitHub release labelled v1.1.1.0 while its README header displays 1.1.0. Both are disclosed until reconciled." }], action: { label: "Inspect open-source work", href: "/open-source" } },
  { path: "support", state: "rivers", stateLabel: "Rivers · Continuity", eyebrow: "SUPPORT", title: "The system should remain understandable after launch.", summary: "Maintenance, investigation, recovery and improvement grounded in the active system and agreement.", art: "rivers-support", sections: [{ title: "Existing clients", body: "Use the Client Portal or authenticated project support route for work tied to an active agreement." }, { title: "New support needs", body: "Describe the system, symptoms, recent changes, access state, impact and available backups." }], action: { label: "Describe a support need", href: "/contact" } },
  { path: "support/emergency", state: "rivers", stateLabel: "Rivers · Recovery", eyebrow: "EMERGENCY RECOVERY", title: "Describe what failed and what is at risk.", summary: "For unavailable, compromised, corrupted or severely impaired production systems. Submission does not guarantee immediate response or resolution.", art: "rivers-emergency", sections: [{ title: "Prepare the first record", body: "Share the affected URL or system, visible symptoms, when it began, recent changes, access state and available backups." }, { title: "Response boundary", body: "An initial diagnostic may be chargeable. Coverage and timing depend on availability and the active agreement." }], action: { label: "Prepare an emergency summary", href: "/contact?route=emergency" } },
  { path: "knowledge-base", state: "rivers", stateLabel: "Rivers · Operating records", eyebrow: "KNOWLEDGE BASE", title: "Answers for operating the system.", summary: "A structured home for verified platform, publishing, hosting, security, billing and support guidance.", art: "rivers-support", sections: [{ title: "Publishing platforms", body: "OJS administration, workflow, upgrades, plugins and editorial operations." }, { title: "Websites and infrastructure", body: "Access, hosting, domains, email, backups, monitoring and recovery." }] },
  { path: "status", state: "rivers", stateLabel: "Rivers · Service state", eyebrow: "STATUS", title: "No live service feed is connected.", summary: "This page refuses to simulate operational status. Verified monitoring integration remains a launch decision.", art: "rivers-infrastructure", sections: [{ title: "Current state", body: "No public uptime, incident or component data is available from a verified endpoint." }] },
  { path: "security", state: "rivers", stateLabel: "Rivers · Security", eyebrow: "SECURITY", title: "Security is an operating practice.", summary: "Controlled access, secure defaults, backups, monitoring, recovery and documented responsibility.", art: "rivers-infrastructure", sections: [{ title: "Responsible disclosure", body: "Report suspected security issues privately to hello@airixmedia.com. Do not include credentials or secrets in the first message." }, { title: "Evidence before badges", body: "No certification, partnership or control claim appears without current verification." }] },
  { path: "service-levels", state: "rivers", stateLabel: "Rivers · Service levels", eyebrow: "SERVICE LEVELS", title: "Commitments belong to the agreement.", summary: "Coverage, response and resolution depend on the system, provider, access and purchased package.", art: "rivers-support", sections: [{ title: "Response is not resolution", body: "A response confirms receipt and triage. Resolution depends on diagnosis, dependencies, access and scope." }] },
  { path: "studio", state: "edo", stateLabel: "Edo · Studio", eyebrow: "STUDIO", title: "Small by design. Accountable by practice.", summary: "Airix Media is a boutique creative technology studio and digital operations partner within Airix 360.", art: "edo-studio", sections: [{ title: "How Airix works", body: "Senior oversight, explicit responsibility, evidence-led decisions and a practical relationship after launch." }, { title: "Part of Airix 360", body: "Airix Media is described at brand level only. Entity, jurisdiction and final legal language remain pending verification." }], action: { label: "Discuss a project", href: "/discuss" } },
  { path: "open-source", state: "kaduna", stateLabel: "Kaduna · Labs", eyebrow: "OPEN SOURCE", title: "Useful publishing infrastructure, improved in public.", summary: "Verified repositories with release state, documentation and limitations made visible.", art: "kaduna-labs", sections: [{ title: "Five public records", body: "PaystackOJS, OJS Magic Login, Submission Fee, MultiPay and Request Waiver. Private repository names and contents are never exposed." }] },
  { path: "atlas", state: "plateau", stateLabel: "Plateau · Observatory", eyebrow: "AIRIX ATLAS", title: "A wider view of the systems organisations depend on.", summary: "Atlas turns infrastructure, exchange, knowledge, making and stewardship into one navigable Nigerian world.", art: "plateau-observatory", sections: [{ title: "Build worlds, not pages", body: "Place, movement and infrastructure make technical responsibility easier to understand without replacing clear public labels." }] },
  { path: "insights", state: "plateau", stateLabel: "Plateau · Field notes", eyebrow: "INSIGHTS", title: "Practical thinking for people who operate digital systems.", summary: "Publishing technology, recovery, infrastructure and workflow design without generic filler.", art: "plateau-insights", sections: [{ title: "Featured field note", body: "Planning an OJS upgrade without turning production into a test environment." }] },
  { path: "resources", state: "plateau", stateLabel: "Plateau · Resources", eyebrow: "RESOURCES", title: "Useful tools before you start a project.", summary: "Clear review prompts for ownership, risk, access and the next practical decision.", art: "plateau-resources", sections: [{ title: "Publication boundary", body: "Downloadable files remain unavailable until real resources, ownership, accessibility and versioning are verified." }] },
  { path: "discuss", state: "ogun", stateLabel: "Ogun · Gateway", eyebrow: "DISCUSS A PROJECT", title: "Where shall we build next?", summary: "Start with the organisation, the challenge and what is at risk. The local summary helps shape a useful conversation.", art: "ogun-gateway", sections: [{ title: "A qualified first brief", body: "Choose a route, describe the current system, timing, budget context and support need. Nothing is transmitted without a verified endpoint." }], action: { label: "Prepare the brief", href: "#project-brief" } },
  { path: "contact", state: "ogun", stateLabel: "Ogun · Contact", eyebrow: "CONTACT", title: "Tell us what needs to work better.", summary: "Prepare a local message summary or use a verified direct channel. No form submission is simulated.", art: "ogun-contact", sections: [{ title: "Verified channels", body: "hello@airixmedia.com · +234 905 091 7937 · WhatsApp available on the Nigerian number." }], action: { label: "Prepare a message", href: "#contact-summary" } },
  { path: "book", state: "ogun", stateLabel: "Ogun · Booking", eyebrow: "BOOK A CONVERSATION", title: "A useful conversation starts with context.", summary: "No scheduling provider or availability endpoint is verified. Prepare meeting context, then continue through email.", art: "ogun-booking", sections: [{ title: "No fake calendar", body: "The site does not expose invented slots, holds or appointment confirmations." }], action: { label: "Prepare a project brief", href: "/discuss" } },
  { path: "legal", state: "shared", stateLabel: "Airix Media · Legal", eyebrow: "LEGAL CENTRE", title: "Draft structure awaiting legal review.", summary: "Privacy, terms, cookies, accessibility, regional pricing and data-processing language are not final legal advice.", sections: [{ title: "Publication blocker", body: "Entity identity, jurisdiction, controller details, lawful basis, retention and final service terms require legal approval before launch." }] }
];

const detailFallbacks: Array<[string, PublicPage]> = [
  ["work/", { ...publicPages[0], path: "work/detail", eyebrow: "WORK RECORD", title: "Verified project record", summary: "Only source-captured evidence and approved responsibility statements appear here." }],
  ["open-source/", { ...publicPages.find((p) => p.path === "open-source")!, path: "open-source/detail", eyebrow: "PUBLIC REPOSITORY", title: "Open-source project record", summary: "Repository purpose, release state, compatibility notes and limitations remain explicit." }],
  ["insights/", { ...publicPages.find((p) => p.path === "insights")!, path: "insights/detail", title: "Plan an OJS upgrade without testing in production", summary: "Inventory, staging, compatibility, validation, rollback and communication before production change." }],
  ["resources/", { ...publicPages.find((p) => p.path === "resources")!, path: "resources/detail", title: "Digital Systems Health Checklist", summary: "A structured review of ownership, access, performance, security, analytics, backups and support." }]
];

export function getPublicPage(path: string) {
  if (path === "work/ku-journals") return {
    path,
    state: "oyo" as const,
    stateLabel: "Oyo · Publishing evidence",
    eyebrow: "SOURCE-CAPTURED WORK RECORD",
    title: "KU Journals",
    summary: "A current public journal interface whose footer credits Airix Media with design, development and maintenance.",
    art: "oyo-publishing" as const,
    sections: [
      { title: "What the public record supports", body: "The live interface and dated captures support the existence of the platform and the visible Airix Media footer credit." },
      { title: "What remains withheld", body: "Original need, constraints, complete responsibility, editorial decisions, institutional claims, journal metrics and measurable outcomes remain unverified." }
    ],
    action: { label: "Discuss a publishing system", href: "/discuss" }
  };
  if (path.startsWith("open-source/")) {
    const names: Record<string, string> = { "paystack-ojs": "PaystackOJS", "ojs-magic-login": "OJS Magic Login", "submission-fee": "Submission Fee for OJS", multipay: "MultiPay for OJS", "request-waiver": "Request Waiver for OJS" };
    const slug = path.split("/")[1];
    if (names[slug]) return { ...publicPages.find((page) => page.path === "open-source")!, path, eyebrow: "VERIFIED PUBLIC REPOSITORY", title: names[slug], summary: slug === "paystack-ojs" ? "A public OJS 3.5 Paystack payment plugin. GitHub release v1.1.1.0 and README header 1.1.0 are both disclosed." : "A public OJS plugin record with source, release state and support boundaries kept explicit." };
  }
  return publicPages.find((page) => page.path === path) ?? detailFallbacks.find(([prefix]) => path.startsWith(prefix))?.[1] ?? null;
}

export const publishingPrices = [
  ["OJS setup", "From ₦150,000"],
  ["Migration", "From ₦200,000"],
  ["Theme and branding", "From ₦150,000"],
  ["Managed hosting, domain, SSL and Cloudflare", "From ₦300,000/year"],
  ["Support and maintenance", "From ₦150,000/year"],
  ["Training · up to 10 participants", "From ₦100,000/session"],
  ["Custom plugins", "From ₦250,000"]
] as const;
