"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, ArrowRight, Mail, Printer, Save } from "lucide-react";
import { useEffect, useState, type MouseEvent } from "react";
import { useForm, useWatch } from "react-hook-form";
import { projectBriefSchema, recommendBrief, type ProjectBrief } from "@/lib/selector";
import type { Locale } from "@/lib/content";

const defaults: ProjectBrief = { organisationType: "", challenge: "", requestedService: "", existingPlatform: "", websiteUrl: "", projectType: "new", urgency: "planned", launchWindow: "", budget: "", billingCountry: "NG", ongoingSupport: true, consent: true };

const labels = {
  en: { organisation: "Organisation type", choose: "Choose one", challenge: "What needs to work better?", projectType: "Project type", service: "Requested service", platform: "Existing platform", url: "Current website or system URL", files: "Files or screenshots", upload: "Upload handling is represented but disabled in prototype mode.", urgency: "Urgency", launch: "Desired launch window", budget: "Approximate budget", country: "Billing country", support: "Include ongoing support in the recommendation", recommendation: "PRELIMINARY RECOMMENDATION", consent: "I agree that Airix may use this information to review and respond to my enquiry.", back: "Back", continue: "Continue", submit: "Submit brief", save: "Save", print: "Print", email: "Email" },
  fr: { organisation: "Type d’organisation", choose: "Choisir", challenge: "Qu’est-ce qui doit mieux fonctionner ?", projectType: "Type de projet", service: "Service demandé", platform: "Plateforme actuelle", url: "URL du site ou système actuel", files: "Fichiers ou captures", upload: "Le téléversement est représenté mais désactivé dans le prototype.", urgency: "Urgence", launch: "Période de lancement souhaitée", budget: "Budget approximatif", country: "Pays de facturation", support: "Inclure un accompagnement continu", recommendation: "RECOMMANDATION PRÉLIMINAIRE", consent: "J’accepte qu’Airix utilise ces informations pour examiner ma demande et y répondre.", back: "Retour", continue: "Continuer", submit: "Envoyer le brief", save: "Enregistrer", print: "Imprimer", email: "Envoyer" },
  pt: { organisation: "Tipo de organização", choose: "Escolher", challenge: "O que precisa de funcionar melhor?", projectType: "Tipo de projeto", service: "Serviço solicitado", platform: "Plataforma atual", url: "URL do site ou sistema atual", files: "Ficheiros ou capturas", upload: "O carregamento está representado, mas desativado no protótipo.", urgency: "Urgência", launch: "Janela de lançamento pretendida", budget: "Orçamento aproximado", country: "País de faturação", support: "Incluir suporte contínuo na recomendação", recommendation: "RECOMENDAÇÃO PRELIMINAR", consent: "Concordo que a Airix utilize estas informações para analisar e responder ao meu pedido.", back: "Voltar", continue: "Continuar", submit: "Enviar briefing", save: "Guardar", print: "Imprimir", email: "Enviar" },
};

export function ProjectSelector({ locale = "en", presetEmergency = false }: { locale?: Locale; presetEmergency?: boolean }) {
  const t = labels[locale];
  const [step, setStep] = useState(0);
  const [submitted, setSubmitted] = useState<{ reference?: string; mode?: string } | null>(null);
  const [serverError, setServerError] = useState("");
  const { register, handleSubmit, control, reset, trigger, formState: { errors, isSubmitting } } = useForm<ProjectBrief>({ resolver: zodResolver(projectBriefSchema), defaultValues: presetEmergency ? { ...defaults, requestedService: "support", projectType: "rescue", urgency: "emergency" } : defaults });
  const values = useWatch({ control }) as ProjectBrief;
  useEffect(() => { const saved = localStorage.getItem("airix_project_brief"); if (saved) { try { reset(JSON.parse(saved)); } catch {} } }, [reset]);

  async function next(event: MouseEvent<HTMLButtonElement>) {
    event.preventDefault();
    const groups: (keyof ProjectBrief)[][] = [["organisationType", "challenge", "projectType"], ["requestedService", "existingPlatform", "websiteUrl"], ["urgency", "launchWindow", "budget", "billingCountry"]];
    if (await trigger(groups[step])) setStep((value) => Math.min(3, value + 1));
  }
  function save() { localStorage.setItem("airix_project_brief", JSON.stringify(values)); setServerError("Brief saved on this device."); }
  async function submit(data: ProjectBrief) {
    setServerError("");
    const response = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ brief: data, source: window.location.pathname, companyWebsite: "" }) });
    const result = await response.json();
    if (!response.ok) { setServerError(result.error ?? "The brief could not be submitted."); return; }
    localStorage.removeItem("airix_project_brief"); setSubmitted(result);
  }
  const recommendation = recommendBrief(values);
  const summary = encodeURIComponent(`Airix Media project brief\n\nOrganisation: ${values.organisationType}\nChallenge: ${values.challenge}\nService: ${values.requestedService}\nProject type: ${values.projectType}\nUrgency: ${values.urgency}\nBudget: ${values.budget}\nBilling country: ${values.billingCountry}\nRecommended practice: ${recommendation.practice}`);

  if (submitted) return <div className="result-panel" role="status"><span className="mono">BRIEF RECEIVED · {submitted.mode?.toUpperCase()}</span><h2>Thank you. The next step is human review.</h2><p>Your prototype reference is <strong>{submitted.reference}</strong>. The integration is running in mock mode; no live CRM record or booking has been created.</p><a className="button" href="mailto:hello@airixmedia.com">Email Airix Media</a></div>;

  return <form className="form-shell" onSubmit={handleSubmit(submit)} noValidate>
    <div className="form-progress" aria-label={`Step ${step + 1} of 4`}>{[0,1,2,3].map((item) => <i key={item} className={item <= step ? "active" : ""} />)}</div>
    {step === 0 && <div className="form-grid"><div className="field"><label htmlFor="organisationType">{t.organisation}</label><select id="organisationType" {...register("organisationType")}><option value="">{t.choose}</option><option>Journal or publisher</option><option>University or research institution</option><option>Business or e-commerce</option><option>Association or nonprofit</option><option>Startup</option><option>Agency partner</option><option>Public institution</option></select>{errors.organisationType && <small className="error">{t.choose}</small>}</div><div className="field"><label htmlFor="projectType">{t.projectType}</label><select id="projectType" {...register("projectType")}><option value="new">New system</option><option value="rebuild">Rebuild</option><option value="migration">Migration</option><option value="rescue">Rescue</option></select></div><div className="field full"><label htmlFor="challenge">{t.challenge}</label><textarea id="challenge" {...register("challenge")} placeholder="Describe the problem, who it affects, and what happens if it remains unresolved." />{errors.challenge && <small className="error">{t.choose}</small>}</div></div>}
    {step === 1 && <div className="form-grid"><div className="field"><label htmlFor="requestedService">{t.service}</label><select id="requestedService" {...register("requestedService")}><option value="">{t.choose}</option><option value="website">Website or e-commerce</option><option value="systems">Application, portal, or automation</option><option value="publishing">OJS or publishing technology</option><option value="infrastructure">Hosting or infrastructure</option><option value="support">Support or recovery</option></select>{errors.requestedService && <small className="error">{t.choose}</small>}</div><div className="field"><label htmlFor="existingPlatform">{t.platform}</label><input id="existingPlatform" {...register("existingPlatform")} placeholder="OJS, WordPress, custom, unknown" /></div><div className="field full"><label htmlFor="websiteUrl">{t.url}</label><input id="websiteUrl" inputMode="url" {...register("websiteUrl")} placeholder="https://" />{errors.websiteUrl && <small className="error">Enter a complete URL.</small>}</div><div className="field full"><label htmlFor="files">{t.files}</label><input id="files" type="file" multiple disabled /><small>{t.upload}</small></div></div>}
    {step === 2 && <div className="form-grid"><div className="field"><label htmlFor="urgency">{t.urgency}</label><select id="urgency" {...register("urgency")}><option value="planned">Planned</option><option value="soon">Soon</option><option value="urgent">Urgent</option><option value="emergency">Production emergency</option></select></div><div className="field"><label htmlFor="launchWindow">{t.launch}</label><select id="launchWindow" {...register("launchWindow")}><option value="">{t.choose}</option><option>Within 1 month</option><option>1 to 3 months</option><option>3 to 6 months</option><option>More than 6 months</option><option>Needs assessment</option></select>{errors.launchWindow && <small className="error">{t.choose}</small>}</div><div className="field"><label htmlFor="budget">{t.budget}</label><select id="budget" {...register("budget")}><option value="">{t.choose}</option><option>Under $1,000</option><option>$1,000 to $5,000</option><option>$5,000 to $15,000</option><option>$15,000+</option><option>Needs scoping</option></select>{errors.budget && <small className="error">{t.choose}</small>}</div><div className="field"><label htmlFor="billingCountry">{t.country}</label><input id="billingCountry" maxLength={2} {...register("billingCountry")} placeholder="NG" /><small>ISO 3166-1 alpha-2</small></div><div className="field full"><label><input type="checkbox" {...register("ongoingSupport")} /> {t.support}</label></div></div>}
    {step === 3 && <div className="result-panel"><span className="mono">{t.recommendation}</span><h2>{recommendation.practice}</h2><p>{recommendation.engagement}</p><p>{recommendation.timeline}</p><div className="detail-list">{recommendation.assumptions.map((item) => <div key={item}>{item}</div>)}</div><label className="field"><span><input type="checkbox" {...register("consent")} /> {t.consent}</span></label>{errors.consent && <p className="error">Consent is required to submit the brief.</p>}<div className="rescue-actions"><button type="button" className="button secondary compact" onClick={save}><Save size={16} /> {t.save}</button><button type="button" className="button secondary compact" onClick={() => window.print()}><Printer size={16} /> {t.print}</button><a className="button secondary compact" href={`mailto:?subject=Airix Media project brief&body=${summary}`}><Mail size={16} /> {t.email}</a></div></div>}
    {serverError && <p role="status" className={serverError.includes("saved") ? "" : "error"}>{serverError}</p>}
    <div className="form-actions">{step > 0 ? <button type="button" className="button secondary" onClick={() => setStep((value) => value - 1)}><ArrowLeft size={18} /> {t.back}</button> : <span />}{step < 3 ? <button type="button" className="button" onClick={next}>{t.continue} <ArrowRight size={18} /></button> : <button type="submit" className="button" disabled={isSubmitting}>{isSubmitting ? "…" : t.submit} <ArrowRight size={18} /></button>}</div>
  </form>;
}
