import { routeHeroAssets } from "@/lib/atlas/route-heroes";
import styles from "./review.module.css";

export default function OwnerReviewR2() {
  return <main className={styles.review}>
    <header><span>PRIVATE · NOINDEX · OWNER REVIEW R2</span><h1>Route artwork integration register.</h1><p>Day and night runtime derivatives are shown below. Candidate status and institutional safeguards are private review metadata, not public route copy.</p></header>
    {Object.values(routeHeroAssets).map((asset) => <section key={asset.route} data-review-route={asset.route}>
      <div className={styles.heading}><div><span>{asset.status}</span><h2>{asset.route}</h2><p>Mobile focal position: {asset.mobilePosition}. Active runtime asset is selected by the resolved theme; the inactive asset is not requested by the public route.</p>{asset.internalContext && <p className={styles.warning}>{asset.internalContext}</p>}</div><dl><div><dt>Day</dt><dd>{asset.day.split("/").at(-1)}</dd></div><div><dt>Night</dt><dd>{asset.night.split("/").at(-1)}</dd></div></dl></div>
      <div className={styles.assets}><figure><img src={asset.day} alt=""/><figcaption>Daytime asset</figcaption></figure><figure><img src={asset.night} alt=""/><figcaption>Nighttime asset</figcaption></figure></div>
      <p className={styles.captureNote}>Desktop, 390px and 360px route captures are generated by the R2 route screenshot audit and stored with the review deliverable.</p>
    </section>)}
  </main>;
}
