import Link from "next/link";
import { legalDocuments, legalReviewStatus } from "@/content/legal";
import { publicPages } from "@/content/atlas/public";
import { openSourceProjects } from "@/lib/content";
import styles from "./owner-review.module.css";

const routes = [{ path: "/", purpose: "Homepage and broad proposition", art: "candidate-arrival" }, ...publicPages.map((page) => ({ path: `/${page.path}`, purpose: page.title, art: page.art ? `candidate-${page.art}` : "none" })), { path: "/work/ku-journals", purpose: "Public evidence record", art: "candidate-publishing" }, ...openSourceProjects.map((project) => ({ path: `/open-source/${project.slug}`, purpose: project.name, art: "candidate-labs" })), { path: "/publishing/pricing", purpose: "OJS pricing", art: "blocked-market-square" }, ...legalDocuments.map((item) => ({ path: `/${item.path}`, purpose: item.purpose, art: "legal-pending" }))];

export default function OwnerReviewR1() { return <main className={styles.ownerReview}><header><span>PRIVATE · NOINDEX · OWNER REVIEW R1.1</span><h1>Corrected visual and legal review.</h1><p>Every review capture is generated from this branch. Geographic assignments, legal review status and artwork provenance remain private.</p><p className={styles.disclosure}>Current hero candidates are repeated where noted; Pricing remains blocked pending the approved market-square artwork. Review selections and notes are not saved or transmitted.</p></header><nav className={styles.ownerToc} aria-label="Owner review contents">{routes.map((route) => <a key={route.path} href={`#${route.path === "/" ? "home" : route.path.slice(1).replaceAll("/", "-")}`}>{route.path}</a>)}</nav><div>{routes.map((route) => { const id = route.path === "/" ? "home" : route.path.slice(1).replaceAll("/", "-"); const disclosure = route.path === "/publishing/pricing" ? "Artwork blocked — awaiting the approved market-square image." : route.art === "none" || route.art === "legal-pending" ? "Artwork pending — no hero is represented as complete." : "Candidate artwork — this image may be repeated across routes and is not presented as unique."; return <section className={styles.ownerRoute} id={id} key={route.path}><div><span>{route.art}</span><h2>{route.path}</h2><p>{route.purpose}</p><p className={styles.disclosure}>{disclosure}</p></div><fieldset><legend>Visual review</legend>{["Retain", "Revise", "Replace artwork", "Needs closer review"].map((choice) => <label key={choice}><input type="radio" name={route.path} /> {choice}</label>)}</fieldset><label>Owner notes<textarea placeholder="Copy notes manually before closing." /></label><Link href={route.path}>Open live route</Link></section>; })}</div><section className={styles.ownerLegal}><h2>Legal-page evidence</h2><p>{legalReviewStatus}</p>{legalDocuments.map((document) => <p key={document.path}><Link href={`/${document.path}`}>{document.name}</Link> — separate full-page review capture required.</p>)}</section></main>; }
